dataset_dir: ./dataset

collect:
  recorder: ${recorder}
  num_samples: 1000_000
  max_scramble_steps: 17

data:
  dataset_dir: ${dataset_dir}
  batch_size: 128
  num_workers: 16

train:
  max_epochs: 9999999
  accelerator: "mps"
  learning_rate: 1e-3

recorder:
  dataset_dir: ${dataset_dir}
  items_per_file: 10000

model:
  input_size: 324
  hidden_size: 1024
  num_blocks: 10
  output_size: 100