dataset_dir: ./dataset

collect:
  recorder: ${recorder}
  num_samples: 1000
  max_scramble_steps: 40

data:
  dataset_dir: ${dataset_dir}
  batch_size: 128
  num_workers: 16

train:
  max_epochs: 10
  accelerator: "mps"
  learning_rate: 1e-3

recorder:
  dataset_dir: ${dataset_dir}

model:
  input_size: 54
  output_size: 64